/* STEP-01: Database Exploration */
--- Exploring all the objects in the database
select * from INFORMATION_SCHEMA.TABLES;

--- Exploring all the columns in the customer dataset
select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'dim_customers';

--- Exploring all the columns in the products dataset
select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'dim_products';

--- Exploring all the columns in the fact_sales dataset
select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'fact_sales';

/* STEP-02: Dimension Exploration */

--- Explore the countries where the customers come from
select distinct country
from gold.dim_customers;

--- Explore all the major categories
select distinct category, subcategory, product_name
from gold.dim_products
order by 1,2,3;

/* Data Exploration */
--- Find the date of the first and last order
--- How many years of sales are available
select min(order_date) as first_order_date,
max(order_date) as latest_order_date,
DATEDIFF(year,min(order_date), max(order_date)) as order_range_years
from gold.fact_sales;

--- Youngest and Oldest customers
select min(birthdate) as oldest_customer,
DATEDIFF(year,min(birthdate),getdate()) as oldest_age,
max(birthdate) as youngest_customer,
DATEDIFF(year,max(birthdate),getdate()) as youngest_age
from gold.dim_customers;

/* Measure Exploration */
-- Find the total sales
select sum(sales_amount) as Total_Sales
from gold.fact_sales;

-- Find how many items are sold
select sum(quantity) as total_items_sold
from gold.fact_sales;

--- Find the average selling price
select avg(price) as avg_selling_price
from gold.fact_sales;

--- Find the total number of orders
select count(order_number) as Total_orders
from gold.fact_sales;

select count(distinct order_number) as Total_orders
from gold.fact_sales;

-- Find the total number of products
select count(product_name) as Total_products
from gold.dim_products;

select count(distinct product_name) as Total_products
from gold.dim_products;

--- Find the total number of customers
select count(customer_key) as Total_customer
from gold.dim_customers;

--- Find the total number of customers who placed an order
select count(distinct customer_key) as Customer_orders
from gold.fact_sales;

-- Generate a report that shows all key metrics of the business
select 'Total Sales' as measure_name, sum(sales_amount) as measure_value from gold.fact_sales
union all
select 'Total Quantity', sum(quantity) as measure_value from gold.fact_sales
union all
select 'Average Selling Price', avg(price) as measure_value from gold.fact_sales
union all
select 'Total No. Order', count(distinct order_number) as measure_value from gold.fact_sales
union all
select 'Total No. Products', count(product_name) as measure_value from gold.dim_products
union all
select 'Total No. Customers', count(customer_key) as measure_value from gold.dim_customers;

/* Magnitude Analysis */
-- Find total customers by country
select country, count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc;

-- Find the total customers by gender
select gender, count(customer_key) as total_customer
from gold.dim_customers
group by gender
order by total_customer desc;

-- Find the total products by category
select category, count(product_key) as total_products
from gold.dim_products
group by category
order by total_products desc;

-- Find the average cost in each category
select category, avg(cost) as avg_cost
from gold.dim_products
group by category
order by avg_cost desc;

--- What is the total revenue generated by each category
select dp.category, sum(f.sales_amount) as total_revenue
from gold.fact_sales as f
left join gold.dim_products as dp
on f.product_key = dp.product_key
group by dp.category
order by total_revenue desc;

--- What is the total revenue generated by each customer
select dc.customer_key,dc.first_name,dc.last_name, sum(f.sales_amount) as total_revenue
from gold.fact_sales as f
left join gold.dim_customers as dc
on f.customer_key = dc.customer_key
group by  dc.customer_key,dc.first_name,dc.last_name
order by total_revenue desc;

--- What is the distribution of items sold across countries
select dc.country, sum(f.quantity) as total_sold_items
from gold.fact_sales as f
left join gold.dim_customers as dc
on f.customer_key = dc.customer_key
group by  dc.country
order by total_sold_items desc;

/* Ranking Analysis */
-- What are the top 5 products that generate highest revenue
select top 5 dp.product_name, sum(f.sales_amount) as total_revenue
from gold.fact_sales as f
left join gold.dim_products as dp
on f.product_key = dp.product_key
group by dp.product_name
order by total_revenue desc;

--- Using window functions
select *
from(
select dp.product_name, sum(f.sales_amount) as total_revenue,
row_number() over (order by sum(f.sales_amount) desc) as ranked_products
from gold.fact_sales as f
left join gold.dim_products as dp
on f.product_key = dp.product_key
group by dp.product_name) as t
where ranked_products <=5;


-- What are the 5 worst performing products in terms of sales
select top 5 dp.product_name, sum(f.sales_amount) as total_revenue
from gold.fact_sales as f
left join gold.dim_products as dp
on f.product_key = dp.product_key
group by dp.product_name
order by total_revenue asc;

--- Find the top 10 customer with the highest revenue
select top 10 dc.customer_key,dc.first_name,dc.last_name, sum(f.sales_amount) as total_revenue
from gold.fact_sales as f
left join gold.dim_customers as dc
on f.customer_key = dc.customer_key
group by  dc.customer_key,dc.first_name,dc.last_name
order by total_revenue desc;

--- Find the 3 customer with the lowest orders placed
select top 3 dc.customer_key,dc.first_name,dc.last_name, count(distinct order_number) as total_order
from gold.fact_sales as f
left join gold.dim_customers as dc
on f.customer_key = dc.customer_key
group by  dc.customer_key,dc.first_name,dc.last_name
order by total_order asc;